name: Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-front:
    name: Build Front
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
  build-functions:
    name: Build Firebase Functions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npm run build-functions
  deploy:
    name: Deploy
    needs: [build-front, build-functions]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
